### PR TITLE
Added CODEOWNERS and MAINTAINERS files

### PR DESCRIPTION
**Pull request by toddysm**
Signed-off-by: Toddy Mladenov <toddysm@gmail.com>

This PR combines all the changes from the following PRs for updating the maintainers for *notaryproject/notation-core-go* sub-project:
[Add Junjie Gao](https://github.com/notaryproject/notation-core-go/pull/114) #114  
[Add Milind Gokarn](https://github.com/notaryproject/notation-core-go/pull/109) #109  
[Add Patrick Zheng](https://github.com/notaryproject/notation-core-go/pull/113) #113  
[Add Pritesh Bandi](https://github.com/notaryproject/notation-core-go/pull/110) #110  
[Add Rakesh Gariganti](https://github.com/notaryproject/notation-core-go/pull/108) #108  
[Add Shiwei Zhang](https://github.com/notaryproject/notation-core-go/pull/112) #112  

The proposal is to abandon the above PRs and merge only this one.

### CODE REVIEW

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Comment by toddysm** [comment]
Linking the issue #106

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by NiazFK — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by SteveLasker — APPROVED** [review]
LGTM
Welcome new maintainers

**Review by justincormack — APPROVED** [review]

**Pull request merged**
