### PR TITLE
fix: revocation response status code should be 200

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Corresponding spec change: https://github.com/notaryproject/specifications/pull/319

### CODE REVIEW

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Comment by Two-Hearts** [comment]
The CI failed, looks like this PR is waiting for #238 to be merged.

**Review by shizhMSFT — DISMISSED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
Looks like tests are failing

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
