### PR TITLE
Add Pritesh Bandi as notation-core-go maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Pritesh Bandi as a seed maintainer of notation-core-go based on [their](https://github.com/notaryproject/notation-core-go/commits?author=priteshbandi) activity as per - https://github.com/notaryproject/notation-core-go/issues/106

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation-core-go/pull/118 was merged

**Pull request closed without merging**
