### PR TITLE
fix: The notation spec link in annotation is unavailable

### PR DESCRIPTION
**Pull request by fanndu**
This is a fix to https://github.com/notaryproject/notation-core-go/issues/155.
That only update the specs address in annotation in order to make the links available.

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
@fanndu The commit 7f2bfa174ba5b829d729fef442287e73faa57e8c is not signed. Could you sign the commit and push again?

**Comment by shizhMSFT** [comment]
@fanndu The DCO is failing. You might want to do rebase instead of merging main.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
