### PR TITLE
chore: updated Notary v2 to Notary Project

### LINKED ISSUE #127: Update references from Notary v2 to Notation
This repo is Notation library, we should update references from Notary v2 to Notation.
Here is a search `Notary v2` in this repo https://github.com/notaryproject/notation-core-go/search?q=%22Notary+v2%22&type=code

Fix the references in code only

### PR DESCRIPTION
**Pull request by Two-Hearts**
This chore PR resolves #127.

This PR also upgraded dependencies of the library.

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
The new feature of untagged COSE_Sign1 will not impact notation signature parsing.

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Pull request merged**
